baseURL = 'https://ghariib.ir/'
languageCode = 'en-us'
title = 'Alireza Gharib Personal Blog'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Alireza Gharib"
  description = "Defending Life, Liberty, and pursuit of Happiness"
  github = "gharib-uk"
  instagram = "gharib.us"
  facebook = "gharib.us"
  twitter = "gharib_us"
  linkedin = "alireza-gharib"
  email = "alireza@gharib.us"
  url = "https://gharib.us"
  keywords = "blog"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  location = "Afterlife"
  enableGitalk = false
  favicon = "/images/github.png"
  avatar = "/images/avatar.jpg"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
